In [1]:
#importing the libraries
import os
import pandas as pd

In [2]:
#reading csv file
data = pd.read_csv("udemy_courses.csv")

#                                            # Data cleaning

In [3]:
data.head(5)

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5 hours,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39 hours,2017-03-09T16:34:20Z,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5 hours,2016-12-19T19:26:30Z,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3 hours,2017-05-30T20:07:24Z,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2 hours,2016-12-13T14:57:18Z,Business Finance

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3683 entries, 0 to 3682
Data columns (total 12 columns):
course_id              3683 non-null int64
course_title           3683 non-null object
url                    3683 non-null object
is_paid                3683 non-null object
price                  3683 non-null object
num_subscribers        3683 non-null int64
num_reviews            3683 non-null int64
num_lectures           3683 non-null int64
level                  3683 non-null object
content_duration       3683 non-null object
published_timestamp    3683 non-null object
subject                3683 non-null object
dtypes: int64(4), object(8)
memory usage: 345.4+ KB

In [5]:
data.head(5)

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5 hours,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39 hours,2017-03-09T16:34:20Z,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5 hours,2016-12-19T19:26:30Z,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3 hours,2017-05-30T20:07:24Z,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2 hours,2016-12-13T14:57:18Z,Business Finance

In [6]:
data.level.unique()

array(['All Levels', 'Intermediate Level', 'Beginner Level',
       'Expert Level', '52'], dtype=object)

In [7]:
data['level'] == '52'

0       False
1       False
2       False
3       False
4       False
        ...
3678    False
3679    False
3680    False
3681    False
3682    False
Name: level, Length: 3683, dtype: bool

In [8]:
data.drop(data.index[data['level'] =='52'],inplace = True)

In [9]:
data.level.unique()

array(['All Levels', 'Intermediate Level', 'Beginner Level',
       'Expert Level'], dtype=object)

In [10]:
data['is_paid'] = data['is_paid'].str.replace('True','1')
data['is_paid'] = data['is_paid'].str.replace('False','0')
data['is_paid'] = data['is_paid'].str.replace('FALSE','0')
data['is_paid'] = data['is_paid'].str.replace('TRUE','1')

In [11]:
data.head(5)

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,1,200,2147,23,51,All Levels,1.5 hours,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,1,75,2792,923,274,All Levels,39 hours,2017-03-09T16:34:20Z,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,1,45,2174,74,51,Intermediate Level,2.5 hours,2016-12-19T19:26:30Z,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,1,95,2451,11,36,All Levels,3 hours,2017-05-30T20:07:24Z,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,1,200,1276,45,26,Intermediate Level,2 hours,2016-12-13T14:57:18Z,Business Finance

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3682 entries, 0 to 3682
Data columns (total 12 columns):
course_id              3682 non-null int64
course_title           3682 non-null object
url                    3682 non-null object
is_paid                3682 non-null object
price                  3682 non-null object
num_subscribers        3682 non-null int64
num_reviews            3682 non-null int64
num_lectures           3682 non-null int64
level                  3682 non-null object
content_duration       3682 non-null object
published_timestamp    3682 non-null object
subject                3682 non-null object
dtypes: int64(4), object(8)
memory usage: 374.0+ KB

In [14]:
data['content_duration'] = data.content_duration.str.split(expand=True)

In [15]:
data

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,1,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,1,75,2792,923,274,All Levels,39,2017-03-09T16:34:20Z,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,1,45,2174,74,51,Intermediate Level,2.5,2016-12-19T19:26:30Z,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,1,95,2451,11,36,All Levels,3,2017-05-30T20:07:24Z,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,1,200,1276,45,26,Intermediate Level,2,2016-12-13T14:57:18Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...,...
3678,775618,Learn jQuery from Scratch - Master of JavaScri...,https://www.udemy.com/easy-jquery-for-beginner...,1,100,1040,14,21,All Levels,2,2016-06-14T17:36:46Z,Web Development
3679,1088178,How To Design A WordPress Website With No Codi...,https://www.udemy.com/how-to-make-a-wordpress-...,1,25,306,3,42,Beginner Level,3.5,2017-03-10T22:24:30Z,Web Development
3680,635248,Learn and Build using Polymer,https://www.udemy.com/learn-and-build-using-po...,1,40,513,169,48,All Levels,3.5,2015-12-30T16:41:42Z,Web Development
3681,905096,CSS Animations: Create Amazing Effects on Your...,https://www.udemy.com/css-animations-create-am...,1,50,300,31,38,All Levels,3,2016-08-11T19:06:15Z,Web Development
3682,297602,Using MODX CMS to Build Websites: A Beginner's...,https://www.udemy.com/using-modx-cms-to-build-...,1,45,901,36,20,Beginner Level,2,2014-09-28T19:51:11Z,Web Development

In [16]:
data.head(5)

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,1,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,1,75,2792,923,274,All Levels,39,2017-03-09T16:34:20Z,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,1,45,2174,74,51,Intermediate Level,2.5,2016-12-19T19:26:30Z,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,1,95,2451,11,36,All Levels,3,2017-05-30T20:07:24Z,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,1,200,1276,45,26,Intermediate Level,2,2016-12-13T14:57:18Z,Business Finance

In [17]:
data['price'].unique()
data['price'] = data['price'].str.replace('Free','0')
data['price']=data['price'].astype(int)

In [18]:
data['content_duration'] = data['content_duration'].astype(float)

In [19]:
data['content_duration'] = data['content_duration']*60

In [20]:
data['content_duration'] = data['content_duration'].astype(int)

# Best Free course by Subject

In [22]:
freecourse = data[(data['is_paid']==0)|(data['price']==0)]

In [23]:
freecourse = freecourse[['course_title','subject','num_subscribers','num_reviews','level']]

In [24]:
freecourse

,course_title,subject,num_subscribers,num_reviews,level
97,Options Trading 101: The Basics,Business Finance,1514,66,Beginner Level
105,Stock Market Investing for Beginners,Business Finance,50855,2698,Beginner Level
108,Fundamentals of Forex Trading,Business Finance,17160,620,All Levels
110,Website Investing 101 - Buying & Selling Onlin...,Business Finance,6811,151,All Levels
114,Stock Market Foundations,Business Finance,19339,794,Beginner Level
...,...,...,...,...,...
3643,Building a Search Engine in PHP & MySQL,Web Development,10110,379,All Levels
3648,CSS Image filters - The modern web images colo...,Web Development,6315,53,All Levels
3656,Drupal 8 Site Building,Web Development,1942,23,All Levels
3670,Beginner Photoshop to HTML5 and CSS3,Web Development,73110,1716,All Levels
3673,A how to guide in HTML,Web Development,7318,205,Beginner Level

In [25]:
freecourse = freecourse.sort_values(by=['subject','num_subscribers'],ascending=[True,False])

In [27]:
freecourse

,course_title,subject,num_subscribers,num_reviews,level
494,Bitcoin or How I Learned to Stop Worrying and ...,Business Finance,65576,936,All Levels
145,Accounting in 60 Minutes - A Brief Introduction,Business Finance,56659,4397,Beginner Level
105,Stock Market Investing for Beginners,Business Finance,50855,2698,Beginner Level
121,Introduction to Financial Modeling,Business Finance,29167,1463,Intermediate Level
496,Forex Basics,Business Finance,22344,712,Beginner Level
...,...,...,...,...,...
2580,How To Make A Web Page With No Code,Web Development,2214,20,Beginner Level
3335,"Complete Web Development with HTML, CSS and Ja...",Web Development,2097,16,Intermediate Level
3656,Drupal 8 Site Building,Web Development,1942,23,All Levels
3347,HTML and CSS Foundations,Web Development,1544,15,Beginner Level
3116,Introduction to Elm,Web Development,1519,28,Intermediate Level

In [28]:
freecourse.groupby(['subject']).head(1)

,course_title,subject,num_subscribers,num_reviews,level
494,Bitcoin or How I Learned to Stop Worrying and ...,Business Finance,65576,936,All Levels
1465,Photoshop In-Depth: Master all of Photoshop's ...,Graphic Design,53851,1779,All Levels
1900,Free Beginner Electric Guitar Lessons,Musical Instruments,101154,1042,Beginner Level
2832,Learn HTML5 Programming From Scratch,Web Development,268923,8629,All Levels

In [29]:
freecourse.groupby(['level']).head(1)

,course_title,subject,num_subscribers,num_reviews,level
494,Bitcoin or How I Learned to Stop Worrying and ...,Business Finance,65576,936,All Levels
145,Accounting in 60 Minutes - A Brief Introduction,Business Finance,56659,4397,Beginner Level
121,Introduction to Financial Modeling,Business Finance,29167,1463,Intermediate Level

# Most Popular courses

In [30]:
popularcourses = data
popularcourses.head(5)

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,1,200,2147,23,51,All Levels,90,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,1,75,2792,923,274,All Levels,2340,2017-03-09T16:34:20Z,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,1,45,2174,74,51,Intermediate Level,150,2016-12-19T19:26:30Z,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,1,95,2451,11,36,All Levels,180,2017-05-30T20:07:24Z,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,1,200,1276,45,26,Intermediate Level,120,2016-12-13T14:57:18Z,Business Finance

In [39]:
popularcourses = popularcourses.sort_values(by=['num_subscribers'],ascending=[False])
popularcourses

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
2832,41295,Learn HTML5 Programming From Scratch,https://www.udemy.com/learn-html5-programming-...,0,0,268923,8629,45,All Levels,630,2013-02-14T07:03:41Z,Web Development
3037,59014,Coding for Entrepreneurs Basic,https://www.udemy.com/coding-for-entrepreneurs...,0,0,161029,279,27,Beginner Level,210,2013-06-09T15:51:55Z,Web Development
3235,625204,The Web Developer Bootcamp,https://www.udemy.com/the-web-developer-bootcamp/,1,200,121584,27445,342,All Levels,2580,2015-11-02T21:13:27Z,Web Development
2788,173548,Build Your First Website in 1 Week with HTML5 ...,https://www.udemy.com/build-your-first-website...,0,0,120291,5924,30,Beginner Level,180,2014-04-08T16:21:30Z,Web Development
3237,764164,The Complete Web Developer Course 2.0,https://www.udemy.com/the-complete-web-develop...,1,200,114512,22412,304,All Levels,1830,2016-03-08T22:28:36Z,Web Development
...,...,...,...,...,...,...,...,...,...,...,...,...
2403,1026760,Coaching Course: Rhythm Instruction for Music ...,https://www.udemy.com/coaching-bundle-rhythm-i...,1,130,0,0,6,All Levels,1920,2017-03-10T16:55:04Z,Musical Instruments
2404,1223240,Learn Pirates of the Caribbean by Ear on the P...,https://www.udemy.com/learn-pirates-of-the-car...,1,20,0,0,6,All Levels,1920,2017-05-22T17:14:43Z,Musical Instruments
894,1219820,Accounting - The 6 most important rules you mu...,https://www.udemy.com/accounting-the-6-most-im...,1,20,0,0,9,All Levels,60,2017-05-25T21:55:50Z,Business Finance
1622,1047408,Easy Coloring Book Design,https://www.udemy.com/easy-coloring-book-design/,1,25,0,0,9,Beginner Level,2100,2016-12-22T00:46:38Z,Graphic Design
887,1057040,Teeter-Totter Accounting,https://www.udemy.com/teeter-totter-accounting/,1,90,0,0,12,Beginner Level,60,2017-02-08T22:15:56Z,Business Finance

# Most Engaged Courses

In [40]:
engangingcourses = data
engangingcourses.sort_values(by=['num_reviews'],ascending=[False])

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
3235,625204,The Web Developer Bootcamp,https://www.udemy.com/the-web-developer-bootcamp/,1,200,121584,27445,342,All Levels,2580,2015-11-02T21:13:27Z,Web Development
3237,764164,The Complete Web Developer Course 2.0,https://www.udemy.com/the-complete-web-develop...,1,200,114512,22412,304,All Levels,1830,2016-03-08T22:28:36Z,Web Development
3209,756150,Angular 4 (formerly Angular 2) - The Complete ...,https://www.udemy.com/the-complete-guide-to-an...,1,190,73783,19649,329,All Levels,1320,2016-02-11T07:29:29Z,Web Development
3252,364426,JavaScript: Understanding the Weird Parts,https://www.udemy.com/understand-javascript/,1,175,79612,16976,85,All Levels,690,2015-03-12T23:19:54Z,Web Development
3259,705264,Modern React with Redux,https://www.udemy.com/react-redux/,1,180,50815,15117,150,All Levels,1590,2015-12-28T19:20:21Z,Web Development
...,...,...,...,...,...,...,...,...,...,...,...,...
1239,1185898,Photoshop - Creación de Efectos 2,https://www.udemy.com/photoshop-creacion-de-ef...,1,30,0,0,9,Beginner Level,60,2017-05-17T19:19:18Z,Graphic Design
1238,185526,MicroStation - Células,https://www.udemy.com/microstation-celulas/,1,20,0,0,9,Beginner Level,2220,2014-04-15T21:48:55Z,Graphic Design
1213,1261122,画像加工の初心者でも「１日」で初歩を覚えられる無料講座,https://www.udemy.com/1-tuqndy/,0,0,21,0,18,Beginner Level,60,2017-06-22T15:01:32Z,Graphic Design
1193,1223000,Innovators and innovation: Travel through time!,https://www.udemy.com/innovators-and-innovatio...,1,50,101,0,31,Beginner Level,360,2017-05-25T17:41:10Z,Business Finance
1657,1036766,How to Color Comic Books... with a Mouse,https://www.udemy.com/how-to-color-comic-books...,1,30,7,0,8,All Levels,120,2017-01-03T14:38:04Z,Graphic Design

In [43]:
data['subject'].nunique()

4

In [46]:
datasubject = data.groupby(['subject']).head(1)
datasubject

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,1,200,2147,23,51,All Levels,90,2017-01-18T20:58:58Z,Business Finance
1199,880202,Anatomy and Figure Drawing for Beginners,https://www.udemy.com/anatomy-and-figure-drawi...,1,150,2252,240,111,Beginner Level,1260,2016-06-20T15:31:48Z,Graphic Design
1802,696630,"7 Ways A Beginner Guitarist Can Sound Better, ...",https://www.udemy.com/nationalguitaracademy/,0,0,4529,193,7,Beginner Level,2160,2015-12-21T18:50:50Z,Musical Instruments
2483,28295,Learn Web Designing & HTML5/CSS3 Essentials in...,https://www.udemy.com/build-beautiful-html5-we...,1,75,43285,525,24,All Levels,240,2013-01-03T00:55:31Z,Web Development

# Best Cost benefit Courses

In [49]:
costbenefit=data.sort_values(by=['num_subscribers','price'],ascending=[False,True])
costbenefit

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
2832,41295,Learn HTML5 Programming From Scratch,https://www.udemy.com/learn-html5-programming-...,0,0,268923,8629,45,All Levels,630,2013-02-14T07:03:41Z,Web Development
3037,59014,Coding for Entrepreneurs Basic,https://www.udemy.com/coding-for-entrepreneurs...,0,0,161029,279,27,Beginner Level,210,2013-06-09T15:51:55Z,Web Development
3235,625204,The Web Developer Bootcamp,https://www.udemy.com/the-web-developer-bootcamp/,1,200,121584,27445,342,All Levels,2580,2015-11-02T21:13:27Z,Web Development
2788,173548,Build Your First Website in 1 Week with HTML5 ...,https://www.udemy.com/build-your-first-website...,0,0,120291,5924,30,Beginner Level,180,2014-04-08T16:21:30Z,Web Development
3237,764164,The Complete Web Developer Course 2.0,https://www.udemy.com/the-complete-web-develop...,1,200,114512,22412,304,All Levels,1830,2016-03-08T22:28:36Z,Web Development
...,...,...,...,...,...,...,...,...,...,...,...,...
2405,1026762,Coaching Course: Rhythm Instruction for Music ...,https://www.udemy.com/coaching-bundle-rhythm-i...,1,125,0,0,7,All Levels,2280,2017-03-10T17:06:46Z,Musical Instruments
2403,1026760,Coaching Course: Rhythm Instruction for Music ...,https://www.udemy.com/coaching-bundle-rhythm-i...,1,130,0,0,6,All Levels,1920,2017-03-10T16:55:04Z,Musical Instruments
1628,1275872,The Complete Adobe Spark Course,https://www.udemy.com/the-complete-adobe-spark...,1,150,0,0,29,All Levels,120,2017-07-03T17:39:57Z,Graphic Design
893,715476,The Cuckoo Strategy to get European Funding,https://www.udemy.com/the-cuckoo-strategy-to-g...,1,160,0,0,6,All Levels,60,2016-01-06T02:38:23Z,Business Finance
891,1083744,How to Invest Using ETFs from Former Wall Stre...,https://www.udemy.com/etf-master-class/,1,200,0,0,10,All Levels,120,2017-02-15T22:34:00Z,Business Finance